#ifndef __SM64_DEFMESSAGE_H__
#define __SM64_DEFMESSAGE_H__

#define CH_0                    0x00
#define CH_1                    0x01
#define CH_2                    0x02
#define CH_3                    0x03
#define CH_4                    0x04
#define CH_5                    0x05
#define CH_6                    0x06
#define CH_7                    0x07
#define CH_8                    0x08
#define CH_9                    0x09
#define CH_A                    0x0A
#define CH_B                    0x0B
#define CH_C                    0x0C
#define CH_D                    0x0D
#define CH_E                    0x0E
#define CH_F                    0x0F
#define CH_G                    0x10
#define CH_H                    0x11
#define CH_I                    0x12
#define CH_J                    0x13
#define CH_K                    0x14
#define CH_L                    0x15
#define CH_M                    0x16
#define CH_N                    0x17
#define CH_O                    0x18
#define CH_P                    0x19
#define CH_Q                    0x1A
#define CH_R                    0x1B
#define CH_S                    0x1C
#define CH_T                    0x1D
#define CH_U                    0x1E
#define CH_V                    0x1F
#define CH_W                    0x20
#define CH_X                    0x21
#define CH_Y                    0x22
#define CH_Z                    0x23
#define CH_a                    0x24
#define CH_b                    0x25
#define CH_c                    0x26
#define CH_d                    0x27
#define CH_e                    0x28
#define CH_f                    0x29
#define CH_g                    0x2A
#define CH_h                    0x2B
#define CH_i                    0x2C
#define CH_j                    0x2D
#define CH_k                    0x2E
#define CH_l                    0x2F
#define CH_m                    0x30
#define CH_n                    0x31
#define CH_o                    0x32
#define CH_p                    0x33
#define CH_q                    0x34
#define CH_r                    0x35
#define CH_s                    0x36
#define CH_t                    0x37
#define CH_u                    0x38
#define CH_v                    0x39
#define CH_w                    0x3A
#define CH_x                    0x3B
#define CH_y                    0x3C
#define CH_z                    0x3D
#define CH_APOSTROPHE           0x3E
#define CH_PERIOD               0x3F
#define CH_CU                   0x50
#define CH_CD                   0x51
#define CH_CL                   0x52
#define CH_CR                   0x53
#define CH_BA                   0x54
#define CH_BB                   0x55
#define CH_BC                   0x56
#define CH_BZ                   0x57
#define CH_BR                   0x58
#define CH_COMMA                0x6F
#define CH_SPACE                0x9E
#define CH_HYPHEN               0x9F
#define CH_TAB                  0xD0
#define CH_the                  0xD1
#define CH_you                  0xD2
#define CH_FMTINT               0xE0
#define CH_PARENL               0xE1
#define CH_PARENRL              0xE2
#define CH_PARENR               0xE3
#define CH_ARROW                0xE4
#define CH_AMPERSAND            0xE5
#define CH_COLON                0xE6
#define CH_DAKUTEN              0xF0
#define CH_HANDAKUTEN           0xF1
#define CH_EXCLAIM              0xF2
#define CH_PERCENT              0xF3
#define CH_QUESTION             0xF4
#define CH_QUOTEL               0xF5
#define CH_QUOTER               0xF6
#define CH_TILDE                0xF7
#define CH_ELLIPSIS             0xF8
#define CH_COIN                 0xF9
#define CH_STAR                 0xFA
#define CH_CROSS                0xFB
#define CH_BULLET               0xFC
#define CH_NOSTAR               0xFD
#define CH_LF                   0xFE
#define CH_NUL                  0xFF

#define CH16_CROSS              0x32
#define CH16_COIN               0x33
#define CH16_STAR               0x35

#define CH8_PERIOD              0x24

#define SM_MARIOL               0x40
#define SM_MARIOR               0x41

#endif /* __SM64_DEFMESSAGE_H__ */
