#!/usr/bin/env python3

import sys

def syntaxerr():
	sys.stderr.write("%s:%d: syntax error\n" % (fn, ln))
	sys.exit(1)

if len(sys.argv) != 2:
	sys.stderr.write("usage: %s <bnk>\n" % sys.argv[0])
	sys.exit(1)
fn = sys.argv[1]
ln = 0
with open(fn, "r") as f:
	tbl = []
	for line in f:
		ln += 1
		line = line.partition("#")[0].strip()
		if not line: continue
		bnk = []
		for x in line.split():
			if not x.isdigit(): syntaxerr()
			bnk.append(int(x))
		tbl.append(bnk)
print(".data")
ptr = 2*len(tbl)
for bnk in tbl:
	print(".short %d" % ptr)
	ptr += 1+len(bnk)
for bnk in tbl:
	print(".byte %s" % ", ".join([
		"%d" % x for x in [len(bnk)]+bnk
	]))
